name: ThrowableTNT
version: 1.4.2
description: A plugin that makes Minecraft TNT a throwable block.
load: POSTWORLD
author: CodeError
website: https://codeerror.dev/
main: dev.codeerror.throwabletnt.ThrowableTNT
api-version: 1.13
softdepend: [Factions]
commands:
    throwabletnt:
       description: Root command for ThrowableTNT.
       aliases: [ttnt, throwtnt]
permissions:
    throwabletnt.*:
        description: Grants access to all permission nodes in ThrowableTNT.
        default: op
        children:
            throwabletnt.throw: true
            throwabletnt.reload: true
    throwabletnt.throw:
        description: Allows a user to throw TNT.
        default: op
    throwabletnt.reload:
        description: Allows a user to reload ThrowableTNT.
        default: op
