name: ThrowableTNT
version: 1.3
api-version: 1.12, 1.13, 1.14, 1.15
description: A plugin that makes Minecraft TNT a throwable block.
load: POSTWORLD
author: CodeError
website: https://www.codeslab.ca/
main: net.CodeError.throwabletnt.Main
commands:
    throwabletnt:
       description: Root command for ThrowableTNT.
       aliases: [ttnt, throwtnt]
permissions:
    throwabletnt.*:
        description: Grants access to all permission nodes in ThrowableTNT.
        default: op
        children:
            throwabletnt.throw: true
            throwabletnt.reload: true
    throwabletnt.throw:
        description: Allows a user to throw TNT.
        default: op
    throwabletnt.reload:
        description: Allows a user to reload ThrowableTNT.
        default: op
